### ISSUE TITLE
Error running "repo sync -f"

### ISSUE THREAD

**Issue by chavhector** [gumdroid/manifest#8]
Hello, 
I am trying the instructions from the github repository:
https://github.com/gumdroid/manifest
I have tried two times: 
- With a machine running Ubuntu 14.04 32bit.
- With a machine running Ubuntu 14.04 64bit.

For the two attempts, when I run the "repo sync -f" command (I use "-f" to automatically recover from lost connections), the command finishes with this error:

Fetching projects: 100% (367/367), done.  
Syncing work tree:   1% (4/367)  error: in `sync -f`: revision refs/tags/android-4.3_r3.1 in platform/cts not found

I have attached a copy/paste of what terminal logged here:
[log.txt](https://github.com/gumdroid/manifest/files/77489/log.txt)

How can I resolve this issue?

**Comment by ashcharles** [comment]
could you pastebin or give a few more details as to the nature of the error please?

**Comment by chavhector** [comment]
Hello ashcharles,
I accidentally hit the "comment" button without finishing the complete description:

Hello,
I am trying the instructions from the github repository:
https://github.com/gumdroid/manifest
I have tried two times:

```
With a machine running Ubuntu 14.04 32bit.
With a machine running Ubuntu 14.04 64bit.
```

For the two attempts, when I run the "repo sync -f" command (I use "-f" to automatically recover from lost connections), the command finishes with this error:

Fetching projects: 100% (367/367), done.
Syncing work tree: 1% (4/367) error: in sync -f: revision refs/tags/android-4.3_r3.1 in platform/cts not found

I have attached a copy/paste of what terminal logged here:
log.txt

How can I resolve this issue?

**Comment by ashcharles** [comment]
This looks like a sync error of some type---I'm not seeing it on our autobuilders and I can see the tag here [1].  If you manually sync that repository, can you see the tag?

[1] https://android.googlesource.com/platform/cts/+/android-4.3_r3.1

**Comment by chavhector** [comment]
Ashcharles,

First: how do you manually sync? I must say that I am a starter on this Android for Gumstix/Overo build.

Second: I am reading again the instructions in the repository and it mentions: "As of October 2013, the following information only pertains to Gumstix Pepper SBC. Stay tuned for updates on Overo and Duovero"

I am building for an Overo board, so I used these commands:
$ repo init -u git://github.com/gumdroid/manifest.git -b overo
$ repo sync -f

Are the instructions valid for an Overo Board? Specifically, I am building for an Overo Firestorm.

**Comment by ashcharles** [comment]
If you are building for Overo, I recommend using the development branch---this is somewhat experimental at this time:
$ repo init -u git://github.com/gumdroid/manifest.git -b dev/overo
$ repo sync

I'm closing this issue as it is not clear that there is a syncing problem.

**Comment by abiabilesh** [comment]
Hi for the revision instead of the branch name try giving the commit id and it should work :)
